version: '1'
services:
  melita_profile_filter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: Melita Profile Filter
      EGRESS_URL: https://testmp.free.beeceptor.com/
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
      PROFILE_IDS: ''
      MATCHED_URL: ''
